Compiling:	./Sources/*.cpp
	clang++ ./Sources/*.cpp -std=c++17 -o ./Bin/Server -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network
	./Bin/Server "1:192.168.0.6:3412|2:192.168.0.9:7045|3:192.168.0.16:2312|4:192.168.1.45:19345|"